name: Upload Data

on:
  push:
    branches:
    - master
  schedule:
  - cron: "0 13 * * 1"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: actions/cache@v2
      with:
        path: |
          vendor/bundle
          pdfs
        key: ${{ runner.os }}-cache-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-cache-
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Install bundler and run build command
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install
        bundle exec ruby build.rb
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
        SOURCE_DIR: 'data'